apiVersion: v1
kind: Service
metadata:
  labels:
    app: k3s-svc
  name: k3s-svc
spec:
  selector:
    app: k3s-app
  type: NodePort
  ports:
  - name: 80-5000
    port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 30005