name: CI/CD pipeline to build and deploy app

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and Push Image
      run: |
        set -e
        IMAGE=${{ secrets.DOCKER_USERNAME }}/k3s-app:${{ github.sha }}
        
        echo "Deploying image: $IMAGE"

        docker build -t $IMAGE -f docker/Dockerfile .
        docker push $IMAGE

    - name: Deploy to k3s
      run: |
        set -e

        IMAGE=${{ secrets.DOCKER_USERNAME }}/k3s-app:${{ github.sha }}

        echo "Deploying image: $IMAGE"

        sed -i "s|image: .*|image: $IMAGE|" k8s/k3s-app.yaml

        kubectl apply -f k8s/

        # Wait for rollout
        kubectl rollout status deployment/k3s-app --timeout=180s || {
          echo "Rollout failed"

          # Try rollback (if not possible)
          kubectl rollout undo deployment/k3s-app || true

          exit 1
        }

