name: CI/CD pipeline to build and deploy app

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and Push Image
      run: |
        set -e
        IMAGE=${{ secrets.DOCKER_USERNAME }}/k3s-app:${{ github.sha }}
        
        echo "Deploying image: $IMAGE"

        docker build -t $IMAGE -f docker/Dockerfile .
        docker push $IMAGE

    - name: Deploy to k3s
      run: |
        set -e

        IMAGE=${{ secrets.DOCKER_USERNAME }}/k3s-app:${{ github.sha }}

        # Deploy new image
        kubectl set image deployment/k3s-app k3s-app=$IMAGE

        # Add rollout message
        kubectl annotate deployment/k3s-app \
          kubernetes.io/change-cause="${{ github.sha }} - ${{ github.event.head_commit.message }}" \
          --overwrite

        # Wait for rollout, rollback if failed
        kubectl rollout status deployment/k3s-app --timeout=180s || \
        (echo "Rollout failed. Rolling back..." && kubectl rollout undo deployment/k3s-app && exit 1)